# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Station:
  fields:
    list: name, url
    form: name, url
  order_by:
  relationships: users
  filters:
  search: name
  application: SP-Gestion

User:
  fields:
    list: email, login_count, failed_login_count, last_login_at, confirmed_at, confirmation_sent_at, last_boosted_at, station
    form: email, station
    show: email, station, perishable_token
    options:
      date_formats:
        last_login_at: short
        confirmed_at: short
        confirmation_sent_at: short
        last_boosted_at: short
  order_by:
  relationships: station
  filters:
  search: email
  application: SP-Gestion
  actions:
    edit: boost_activation