# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Station: create, read, update, delete
  User: create, read, update, delete, boost_activation
  Statistics: index