# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

BetaCode:
  fields:
    list: code, email, used, user
    form: code, email, used, user
  order_by: 
  relationships: user
  filters:  used
  search:
  application: SP-Gestion

Newsletter:
  fields:
    list: email, activated_at, last_boosted_at, invited_at
    form: email, activated_at, last_boosted_at, invited_at
    options:
      date_formats:
        activated_at: short
        last_boosted_at: short
        invited_at: short
  order_by:
  relationships: 
  filters: activated_at
  search: email
  application: SP-Gestion
  actions:
    edit: invite_to_beta, boost_activation

Station:
  fields:
    list: name, url
    form: name, url
  order_by: 
  relationships: users
  filters: 
  search: name
  application: SP-Gestion

User:
  fields:
    list: email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip, confirmed_at, confirmation_sent_at, station
    form: email, login_count, failed_login_count, last_request_at, current_login_at, last_login_at, current_login_ip, last_login_ip, confirmed_at, confirmation_sent_at, station
    options:
      date_formats:
        last_request_at: short
        current_login_at: short
        last_login_at: short
        confirmed_at: short
        confirmation_sent_at: short
  order_by: 
  relationships: beta_codes, station
  filters: 
  search: email
  application: SP-Gestion