# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

BetaCode:
  fields:
    list: code, email, used, user, last_boosted_at
    form: code, email, used, user
  options:
    date_formats:
      last_boosted_at: short    
  order_by: 
  relationships: user
  filters:
  search:
  application: SP-Gestion
  actions:
    edit: boost_activation

Newsletter:
  fields:
    list: email, activated_at, last_boosted_at, invited_at
    form: email
    options:
      date_formats:
        activated_at: short
        last_boosted_at: short
        invited_at: short
  order_by:
  relationships: 
  filters:
  search: email
  application: SP-Gestion
  actions:
    edit: invite_to_beta, boost_activation

Station:
  fields:
    list: name, url
    form: name, url
  order_by: 
  relationships: users
  filters: 
  search: name
  application: SP-Gestion

User:
  fields:
    list: email, login_count, failed_login_count, last_login_at, confirmed_at, confirmation_sent_at, last_boosted_at, station
    form: email, station
    show: email, station, perishable_token
    options:
      date_formats:
        last_login_at: short
        confirmed_at: short
        confirmation_sent_at: short
        last_boosted_at: short
  order_by: 
  relationships: beta_codes, station
  filters: 
  search: email
  application: SP-Gestion
  actions:
    edit: boost_activation