--- 
pid: tmp/pids/thin.pid
log: log/thin.log
max_conns: 1024
timeout: 30
port: 3010
chdir: /home/raphael/public_html/sp-gestion.fr/current
max_persistent_conns: 512
environment: production
servers: 4
daemonize: true
address: 0.0.0.0
require: []